### ISSUE TITLE
Suggestion: Online Staff (staff-online) Placeholder addition

### ISSUE THREAD

**Issue by Portanna** [konsolas/ConditionalCommands#2]
**Suggestion:** Adding a new placeholder as a number of the players online with a certain permission (for example "aac.notify"), in order to know if there is any staff online that can monitor the hack notifications.

**Suggested use:** Could be useful if you want to make a configuration that is both automatic and manual, in a way that the automatic kick is cancelled if there is staff online and if there isn't it will just kick the player for hacks. In my opinion this could improve a lot the plugin capabilities.

**Example config:**

>    thresholds:
>       5: "conditionalcommands:cc {player} if -tps->19 do aacstaffnotify {player} is gonna be kicked"
>       15: "conditionalcommands:cc {player} if -staff-online-<0&-tps->19 do aackick {player} Kicked for Hax"

**Comment by Janmm14** [comment]
Currntly supported through `-perm:aac.notify=1-`
