### ISSUE TITLE
Reduce/eliminate verbose for missing player

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/ConditionalCommands#4]
Can you remove or change the failure message when a player is not online for when CC is being run on them? I know you may think that is already the case with your "player offline" message, but read on...

When you have a stack of AAC kick thresholds running multiple CC commands and a player skyrockets fast enough in hack violations to trip 2+ of them(up to 8 conditions in a split second), it tosses out this warning(below) suggesting the command is improperly parsed when in reality the CC process gets confused when the player is _online_ for the start of the command registering, but _offline_ when it comes time to process the condition (after they were kicked for meeting a lower condition). This is obviously rarer than the "player is not online" message for when the command is started when a player is already gone, but the unique chain of events explained above confuses CC and just calls the user (me) an idiot and also causes some false spam.

http://i.imgur.com/5BuBAD6.png

If the warning could be voided for when the player comes up missing, that would cause a lot less confusion and reduce silly spam.

Example of line that is supposedly incorrect:
"conditionalcommands:cc {player} if (-ping-<100&-ping->0)&-tps->19.9&-time_online->4000&-uptime->200 do aacstaffnotify {player} was kicked for hacks > Badpackets > PING/TPS={ping}/{tps}"

**Comment by mibby** [comment]
@konsolas I'd also like to see a fix for this or option to disable the verbose if at all possible. 
Using ConditionalCommands v1.3 (compiled as of https://github.com/konsolas/ConditionalCommands/commit/fed84211fcf88075ea52b516581801cda4d78345) with @MarkElf's custom NoCheatPlus configuration.

https://paste.ubuntu.com/24961640/

**Comment by konsolas** [comment]
Developer mode was added. These messages are now suppressed by default.
