### ISSUE TITLE
Multiple Commands per Condition

### ISSUE THREAD

**Issue by CeIebrimbor** [konsolas/ConditionalCommands#5]
Simple request to allow multiple commands to be run for a single condition. If the condition fails, all commands fail. If it succeeds, than all commands succeed in order.

**Example:**
"cc {player} if -tps->19.9 do (command1; command2)"

This could also open up the door for conditions _within_ conditions where you can set a secondary command to run only if the previous one in the sequence was a success.

**Example:**
"cc {player} if -tps->19.9 do (command1; cc {player} if -tps->18.0 do command2)"

Currently, to accomplish this outcome you need to stack up conditions and it ends up getting very muddy and causes issues like #4 when you have to run a stack of conditions in a split second.

**Example of mud:**
"cc {player} if -tps->19.9 do command1; cc {player} if -tps->19.9 do command2"
or
       - "cc {player} if -tps->19.9 do command1"
       - "cc {player} if -tps->19.9 do command2"

**Comment by ghost** [comment]
+1

**Comment by konsolas** [comment]
V 1.3
